version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: mottu_postgres
    restart: always
    environment:
      POSTGRES_USER: mottu
      POSTGRES_PASSWORD: mottu123
      POSTGRES_DB: mottu_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: mottu_rabbitmq
    restart: always
    ports:
      - "5672:5672"    # Porta padrão de mensagens
      - "15672:15672"  # Porta da UI de administração

volumes:
  postgres_data:
